### ISSUE TITLE
ДЗ

### ISSUE THREAD

**Issue by azatmagdeev** [azatmagdeev/bonus-homework#1]
@coursar 

https://azatmagdeev.github.io/bonus-homework/

![Снимок экрана (2)](https://user-images.githubusercontent.com/48885231/56084668-930f2900-5e36-11e9-8ba8-c8d1753512a7.png)
 
ошибки

**Comment by coursar** [comment]
Потому что вы в travis.yml написали GITHUB_TOKEN, а в Travis CI GIT_HUB. Зачем?

![Screenshot from 2019-04-15 13-44-47](https://user-images.githubusercontent.com/3601892/56126900-b0eaa400-5f84-11e9-81ab-3310a0b7cb7d.png)
